<header id="header">
    <div id="quick-access">
        <?php echo $this->getChildHtml('topLinks') ?>         
        <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?></p>
        <?php echo $this->getChildHtml('store_language') ?>
    </div>
    <?php if ($this->getIsHomePage()):?>
        <h1 id="site-name">
           <?php echo $this->getLogoAlt() ?>
        </h1>
    <?php else:?>
        <strong id="site-name"><?php echo $this->getLogoAlt() ?></strong>
    <?php endif;?>     
        
    <?php if(false) echo $this->getChildHtml('cart_header') ?>
    <?php if(false) echo $this->getChildHtml('topSearch') ?>
     <a id="logo" href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>">
        <img src="<?php echo $this->getLogoSrc() ?>"  width="220" height="102" alt="<?php echo $this->getLogoAlt() ?>" />
     </a>  
    <?php echo $this->getChildHtml('topContainer') ?>
    <?php echo $this->getChildHtml('topMenu') ?>
</header>
<?php if ($this->getIsHomePage()):?>
<div id="slider">
    <div class="bg">
        <img src="<?php echo $this->getSkinUrl('images/media/slide-1.jpg') ?>" width="909" height="263" alt="" />       
    </div>
    <div class="note">
        <h2>Увага!</h2>
        <p>Зареэструйтесь в нашому магазині, замовте 2 піци, та отримайте третю в подарунок + безкоштовна доставка!</p>
    </div>
    <span class="prev"></span>
    <span class="next"></span>
</div>
<h1 id="home-desc">Вітаємо Вас на сайті піцерії "Леополі - піца на дровах". Підписуйтесь на наші новини та будьте в курсі усіх подій та акцій піцерії</h1>
<?php else:?>
<div id="text-block">
    <p>Замовте 2 піци та отримайте третю безкоштовно + безкоштовна доставка</p>
</div>
<?php endif;?>